[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "php83Extensions.gd",
  "nodejs_22"
]

[phases.install]
cmds = [
  "node -v",
  "npm -v",
  "composer install --ignore-platform-reqs",
  "npm ci"
]